package exception;

public class ReturnMain {

	public static void main(String[] args) {
		ReturnTry obj=new ReturnTry();
		int n=obj.divide();
		System.out.println(n);
		System.out.println("after calling method");
		// TODO Auto-generated method stub

	}

}
